g++ MessageContext.cpp -c -I  /usr/local/Cellar/zeromq/4.3.2/include/ -I ./ -I /Users/vijaysh3/Vijay/Code/PubSubMessaging/PubSubMessaging/include_binding/cppzmq/
g++ PubSubProxy.cpp -c -I  /usr/local/Cellar/zeromq/4.3.2/include/ -I ./ -I /Users/vijaysh3/Vijay/Code/PubSubMessaging/PubSubMessaging/include_binding/cppzmq/
